# Generated by Django 4.1.7 on 2023-04-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmod1_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personmodel',
            name='ageVal',
        ),
    ]
